# NoPlaceLike Cloud - Free to use for all :)
#
# Deployment Pipeline for Demo Project

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: StorageAccountName
    value: ""
  - name: StorageAccountRG
    value: ""
  - name: TableName
    value: ""

steps:
- task: AzurePowerShell@5
  displayName: Deploy with Azure Storage Table
  env:
      WorkloadName: "NPLCTestWorkload"
      DeploymentName: "Deployment"
  inputs:
    azureSubscription: '' ## Fill here your Service Connection
    ScriptType: 'InlineScript'
    azurePowerShellVersion: 'LatestVersion'
    Inline: |
      Import-Module $(Build.SourcesDirectory)/powershell/Table-Storage.psm1
      Import-Module AzTable

      $DeploymentParameters = Read-TableStorage `
        -StorageAccountName $env:StorageAccountName `
        -TableName $env:TableName `
        -StorageAccountRG $env:StorageAccountRG `
        -PartitionKey $env:WorkloadName `
        -RowKey $env:DeploymentName
      
      New-AzSubscriptionDeployment ` 
        -Location $DeploymentParameters.location `
        -TemplateFile $(Build.SourcesDirectory)/main.bicep `
        -TemplateParameterObject $DeploymentParameters